[tool.black]
line-length=79
skip-magic-trailing-comma=true

[tool.poetry]
name = "minigames"
version = "0.1.0"
description = "Fun minigames for your server."
authors = ["CircuitSacul <circuitsacul@icloud.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8,<3.11"
hikari = "^2.0.0-alpha.108"
apgorm = "^1.0.0b11"
hikari-crescent = "^0.1.0"
cachetools = "^5.2.0"
types-cachetools = "^5.0.1"

[tool.poetry.dev-dependencies]
black = "^22.6.0"
isort = "^5.10.1"
mypy = "^0.961"
flake8 = "^4.0.1"
pytest = "^7.1.2"
nox = "^2022.1.7"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
